### ISSUE TITLE
ID attributes for tables need to be auto incrementing

### ISSUE THREAD

**Issue by johnbuffington** [ComputerMedicTeam/Database#1]

**Comment by EvanFarry** [comment]
CREATE TABLE `Service_Provided` (
 `service_id` int(11) NOT NULL AUTO_INCREMENT,
 `customer_id` int(11) NOT NULL,
 `service_name` varchar(30) NOT NULL,
 `price_charged` int(11) NOT NULL,
 `date` date NOT NULL,
 `duration_minutes` int(11) DEFAULT NULL,
 `duration_hours` int(11) DEFAULT NULL,
 `country` varchar(20) NOT NULL,
 `state` varchar(20) NOT NULL,
 `city` varchar(20) NOT NULL,
 `street` varchar(30) NOT NULL,
 `zip` int(11) NOT NULL,
 `hardware_brand` varchar(15) DEFAULT NULL,
 `operating_system` varchar(15) DEFAULT NULL,
 `onsite` tinyint(1) DEFAULT NULL,
 PRIMARY KEY (`service_id`),
 KEY `customer_id` (`customer_id`),
 CONSTRAINT `Service_Provided_ibfk_1` FOREIGN KEY (`customer_id`) REFERENCES `Customer` (`customer_id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1

**Comment by acm482** [comment]
Fixed.
