### ISSUE TITLE
Row variable issues

### ISSUE THREAD

**Issue by JoshuaQChurch** [ComputerMedicTeam/Database#2]
1. Services_Provided table
-  price_charged needs to be a float. 
-  time_duration --> We need to decide what the unit of measurement is going to be. Does it mean how long the service was in days? Hours? 

2. Customer table
- phone_number should take up to 16 digits, since we are accounting for international numbers
- name should be at least 25 characters. Some customer's could possibly have long names. Again, we are accounting for international customers as well (although it's unlikely)

**Comment by acm482** [comment]
3. What do you guys think about an int for minutes? We can clarify this in the service_provided pages like: 

Duration (in minutes): [       ]

**Comment by JoshuaQChurch** [comment]
What does the time_duration represent exactly?

**Comment by acm482** [comment]
The duration that the job took. If a virus removal took 43 minutes time_duration would be 43.

**Comment by JoshuaQChurch** [comment]
Sounds good :+1:

**Comment by acm482** [comment]
Customer wants Hours and Minutes.
